services:
  postgres-db:
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lab2
    volumes: 
      - postgres-db-data:/var/lib/postgresql/data
      - ./postgres-schema/:/docker-entrypoint-initdb.d/

  mongo-db:
    image: mongo:7.0.4
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)", "localhost:27017/test"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=lab2
    volumes: 
      - mongo-db-data:/data/db
      - ./mongo-schema/:/docker-entrypoint-initdb.d/
      - ./test/:/test

volumes:
  postgres-db-data:
  mongo-db-data: